(()=>{
const V=window.TF18=window.TF18||{};
const UC=__require('src/data/useCases.js');
V.targets=UC.METHOD_TARGETS;V.lures=UC.METHOD_LURES;
V.priority={
'アジ':['アジング','スーパーライトショアジギング'],'メバル':['メバリング'],'アオリイカ':['エギング'],'シーバス':['シーバス','サーフ','ボートシーバス'],'クロダイ・キビレ':['チニング'],'カサゴ・ソイ':['ロックフィッシュ'],'ヒラメ・マゴチ':['サーフ'],'サバ・小型青物':['スーパーライトショアジギング','ライトショアジギング','SLJ'],'イナダ・ワラサ':['ライトショアジギング','ショアジギング','SLJ','オフショアジギング','サーフ'],'ブリ':['ショアジギング','オフショアジギング','ライトショアジギング'],'タチウオ':['タチウオワインド'],'マダコ':['タコエギ'],'マダイ':['タイラバ','SLJ'],'サワラ':['ライトショアジギング','ショアジギング','SLJ','ボートシーバス'],'カンパチ':['オフショアジギング','ショアジギング'],'ブラックバス':['バス'],'ニジマス':['エリアトラウト'],'ヤマメ・イワナ':['渓流ルアー'],'ナマズ':['ナマズ']};
V.mem={scrollTop:0,fishSearch:'',open:new Set()};
V.cover=m=>multi.targets.filter(f=>(V.targets[m]||[]).includes(baseFish(f))).length;
V.rank=m=>{let n=999;for(const f of multi.targets){const i=(V.priority[baseFish(f)]||[]).indexOf(m);if(i>=0)n=Math.min(n,i)}return n};
V.methods=()=>METHODS.filter(m=>m!=='指定なし').map(m=>({method:m,coverage:V.cover(m),priority:V.rank(m)})).filter(x=>x.coverage).sort((a,b)=>b.coverage-a.coverage||a.priority-b.priority||METHODS.indexOf(a.method)-METHODS.indexOf(b.method));
V.weight=f=>FISH_DEFAULT_WEIGHT[f]||FISH_PROFILE[baseFish(f)]?.defaultWeightKg||1;
V.ctx=(f,m)=>({...input,method:m,targetFish:baseFish(f),targetWeightKg:V.weight(f),lureType:(V.lures[m]||[])[0]||'指定なし'});
V.products=(f,m,c)=>sortProductsForInput(PRODUCTS.filter(p=>p.category===c),V.ctx(f,m),true).slice(0,2);
const st=document.createElement('style');st.textContent=`.guided-next{border:2px solid color-mix(in srgb,var(--green) 38%,var(--line));background:linear-gradient(145deg,var(--greenbg),var(--card));margin:12px 0}.guided-next h3{margin:2px 0 5px;font-size:18px}.guided-lead{font-size:12px;color:var(--sub);line-height:1.5;margin-bottom:10px}.method-reco-grid{display:grid;gap:8px}.method-reco{border:1px solid var(--line);border-radius:15px;padding:11px;background:var(--card)}.method-reco.top{border-color:color-mix(in srgb,var(--blue) 55%,var(--line));box-shadow:0 7px 16px rgba(47,107,255,.10)}.method-reco-head{display:flex;justify-content:space-between;gap:8px}.method-reco-name{font-size:15px;font-weight:950}.method-reco-score{font-size:10px;font-weight:900;color:var(--green);background:var(--greenbg);padding:4px 7px;border-radius:999px;white-space:nowrap}.spec-row{display:grid;grid-template-columns:1fr 1fr;gap:5px;margin:8px 0}.spec-mini{padding:7px 8px;border-radius:10px;background:var(--bg);font-size:10px;color:var(--sub)}.spec-mini b{display:block;color:var(--text);font-size:11px}.reco-actions{display:grid;grid-template-columns:1fr 1fr;gap:6px}.reco-actions .mini{min-height:40px}.reco-products{margin-top:8px;border-top:1px solid var(--line);padding-top:7px}.reco-products summary{font-size:11px;font-weight:900;color:var(--blue);padding:4px 0}.reco-product-row{padding:6px 0;border-top:1px dashed var(--line)}.reco-product-label{font-size:10px;color:var(--sub);font-weight:900}.reco-product-name{font-size:11px;font-weight:800;line-height:1.35}.chip.method-recommended{border-color:color-mix(in srgb,var(--green) 55%,var(--line));background:color-mix(in srgb,var(--greenbg) 70%,transparent)}.chip.method-recommended.active{background:var(--blue);border-color:var(--blue);color:#fff}.method-badge{margin-left:4px;padding:2px 5px;border-radius:999px;background:var(--greenbg);color:var(--green);font-size:8px;font-weight:950}.chip.active .method-badge{background:rgba(255,255,255,.2);color:#fff}.flow-note{font-size:11px;color:var(--sub);margin:4px 0 8px}.flow-note b{color:var(--text)}`;document.head.appendChild(st);
})();
